### ISSUE TITLE
Workwrap Text

### ISSUE THREAD

**Issue by MwC-Trexx** [custom-cards/state-element#1]
**Version of the cusom_component**
Current version

**Describe the bug**
When displaying text in the Tautulli card, the movie title wraps onto the next line obscuring the text.

See attached screenshot:
<img width="493" alt="screen shot 2018-10-02 at 4 07 53 pm" src="https://user-images.githubusercontent.com/7128246/46377175-80cd5a80-c65d-11e8-88c7-c4c9fb83b3df.png">

**Comment by ludeeus** [comment]
This element does not do **any** styling at all, so this is controllable by you.
There should be something you can put under `style:` that controls this.
What do you have that now?

**Comment by MwC-Trexx** [comment]
It is setup as follows in Lovelace:

             - type: custom:state-attribute-element
                entity: sensor.tautulli
                attribute: Movie
                show_empty: true
                prefix: "<b style='color: orange; margin-right: 5px'>Most played movie: </b>"
                style:
                  top: 60%
                  left: 15px
                  color: white
                  transform: none
