### ISSUE TITLE
text after the entity value

### ISSUE THREAD

**Issue by tpbillund** [custom-cards/state-element#5]
prefix is adding text in front of the entity value, but how do you add text behind it ?

**Comment by ludeeus** [comment]
You don't, what is the usecase?

**Comment by tpbillund** [comment]
If I want to print the internet speed and call it "Fiber UL" then I will get "Fiber UL: 468" then I wan't the mbps after so i get "Fiber UL: 468 Mbps" but i looked at the code in the JS file and added an "AND" so i now can use "endprefix" so I can get what i wan't.

`
class StateElement extends HTMLElement {
  set hass(hass) {
    const entityId = this.config.entity;
    const prefix_string = this.config.prefix
    const endprefix_string = this.config.endprefix
    const show_empty = this.config.show_empty || false;
    const state = hass.states[entityId].state;
    const card = document.createElement('state-element');
    if (state.length != 0) {
      if (prefix_string && endprefix_string) {
        this.innerHTML = prefix_string + state + endprefix_string;
      } else if (prefix_string) {
      	this.innerHTML = prefix_string + state
      } else if (endprefix_string) {
      	this.innerHTML = state + endprefix_string
      } else {	
        this.innerHTML = state;
      }
    } else if (show_empty == true) {
      if (prefix_string) {
        this.innerHTML = prefix_string + state;
      } else {
        this.innerHTML = state;
      }
    }
  }
  setConfig(config) {
    if (!config.entity) {
      throw new Error('You need to define an entity');
    }
    this.config = config;
  }

  getCardSize() {
    return 1;
  }
}
customElements.define('state-element', StateElement);
`

**Comment by ludeeus** [comment]
That should be the unit of measurement, not a postfix in a custom card.

**Comment by tpbillund** [comment]
ok bad ex. (unit) but sometimes I need to show some other things/longer string, after the state, so yes then i need a postfix :-)
But GREAT work, i'm using the state-element alot, just need the postfix in some cases.
